#!/usr/bin/env bash

set -x

source "$(dirname "$0")/config"

mount | grep zfs | sort | tac | awk '/\/mnt/ {print $3}' | xargs -i{} umount -lf {}

mdadm --stop /dev/md0
mdadm --stop /dev/md1

zpool export tank

cryptsetup luksClose luks-zfs5
cryptsetup luksClose luks-zfs4
cryptsetup luksClose luks-zfs3
cryptsetup luksClose luks-zfs2
cryptsetup luksClose luks-zfs1

## Clear out software raid and partition configurations on disks
for dsk in $rdisk1 $rdisk2 $ddisk1 $ddisk2 $sdisk1; do
  if [ -n "$dsk" ]; then
    for prt in 1 2 3 4; do
      mdadm --zero-superblock --force /dev/disk/$DISKS_BY/$dsk-part$prt
    done
    mdadm --zero-superblock --force /dev/disk/$DISKS_BY/$dsk
    mdadm --zero-superblock --force /dev/disk/$DISKS_BY/$dsk
    sgdisk --zap-all /dev/disk/$DISKS_BY/$dsk
  fi
done
